[[main]]
name = "ğŸ“¢ Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "ğŸ“… Events"
pageRef = "events"
weight = 15

[[main]]
name = "ğŸ› ï¸ Projects"
pageRef = "projects"
weight = 15

[[main]]
name = "ğŸ·ï¸ Tags"
pageRef = "tags"
weight = 20
